#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.testing
Version  : 4.6.1
Release  : 2
URL      : https://pypi.python.org/packages/f9/5f/bc694b25c0e3b4be2c5cd0cb211042bbd5a47b0abf67201bb2269e9854a5/zope.testing-4.6.1.tar.gz
Source0  : https://pypi.python.org/packages/f9/5f/bc694b25c0e3b4be2c5cd0cb211042bbd5a47b0abf67201bb2269e9854a5/zope.testing-4.6.1.tar.gz
Summary  : Zope testing helpers
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.testing-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zope.exceptions
BuildRequires : zope.interface

%description
=================
``zope.testing``
=================
.. image:: https://img.shields.io/pypi/v/zope.testing.svg
:target: https://pypi.python.org/pypi/zope.testing/
:alt: Latest Version

%package python
Summary: python components for the zope.testing package.
Group: Default

%description python
python components for the zope.testing package.


%prep
%setup -q -n zope.testing-4.6.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485823002
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1485823002
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
