#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.testing
Version  : 4.6.2
Release  : 8
URL      : https://pypi.debian.net/zope.testing/zope.testing-4.6.2.tar.gz
Source0  : https://pypi.debian.net/zope.testing/zope.testing-4.6.2.tar.gz
Summary  : Zope testing helpers
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.testing-python3
Requires: zope.testing-python
Requires: setuptools
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
``zope.testing``
        =================

%package python
Summary: python components for the zope.testing package.
Group: Default
Requires: zope.testing-python3

%description python
python components for the zope.testing package.


%package python3
Summary: python3 components for the zope.testing package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zope.testing package.


%prep
%setup -q -n zope.testing-4.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522284405
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
